### ISSUE TITLE
Interaction Service API reference

### ISSUE THREAD

**Issue by adamstallard** [Brightside-Social/brightside#4]
https://github.com/Brightside-F2F/brightside/wiki/Interaction-Service-API-Reference

**Comment by adamstallard** [comment]
@galaxy233 Nice work creating an API doc despite not having much info to go on!

Here's some notes:

All interactions are stored on the client (mobile device) as is the contact book, so getInteraction and getLastInteraction aren't of much use; neither are the methods under the **Social Graph** section.  But there needs to be a way to recover your contacts in case of accidental deletion, so maybe getAllInteractions (or equivalently getAllContacts)

Do you as an end-user need to know whether your contacts are verified unique?  Probably not; 3rd-party apps need to know this, and you might want to know this about yourself--so a request about your own uniqueness status would be useful.

**Account** update public key, update name, delete, etc.  We don't associate any data with the public keys in the graph.  Only 3rd-party apps do that, and how they handle this is up to them.

**Uniqueness Verification** You have the right idea here, but I was thinking of separating that into its own API.

**Comment by galaxy233** [comment]
@adamstallard Thanks for providing some clarification what will be needed in this API. Thinking about the separate layers of the system has given me a better idea of what kind of interfaces will need to be formulated.

getUniqueCount returns the total number of distinct identities in the network. I'm not sure exactly how this could be used, other than providing an overview of the network. It may not be necessary.

The rating system was something I thought of, and could be going in a completely different direction than you had envisioned. It could be used as a factor when developing algorithms to determine uniqueness. Example: something happened during the interaction to make party A think party B is untrustworthy.

Going even further with the rating system, we could implement something similar to the episode of Black Mirror, where each individual is tied to their rating, and people rate each other on each interaction. I don't believe this is what your were thinking for Brightside, but creating something like this would be a very interesting social experiment.

**Comment by adamstallard** [comment]
Reputation systems are one of the three main use-cases for brightside.  Eventually, there will be a full-fledged social network built around brightside, and the reputation scores you're talking about would feature there.  Let's remove that from the interaction service api for now, with the intention of adding it back to the brightside social network later.

On the subject of scores, though, there has been some evolution happening in the Brightside decstack channel.  We're now talking about having a "score" rather than a simple "yes/no" for verification checks. 
The anti-sybil systems output a "score" for every user; before I was thinking of just having a threshold: if you're above it you're verified, but suncho got me thinking and I agree, that since we have the score let's just provide that and let each 3rd-party app decide what they want to do with it; they could have their own set of threshold levels for different types of activities in their app.

**Comment by adamstallard** [comment]
Thinking about languages / frameworks.  How do you feel about node.js?

**Comment by adamstallard** [comment]
This issue was moved to Brightside-Social/brightside-node#2
